[project]
name = 'my-project'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.call-service]
path = 'contracts/xcall/call-service.clar'
clarity_version = 2
epoch = 2.4

[contracts.call-service-receiver-trait]
path = 'contracts/xcall/call-service-receiver-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.call-service-trait]
path = 'contracts/xcall/call-service-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.connection-trait]
path = 'contracts/xcall/connection-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.fee-manage-trait]
path = 'contracts/xcall/fee-manage-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.rlp-decode]
path = 'lib/rlp/rlp-decode.clar'
clarity_version = 2
epoch = 2.4

[contracts.sip-010-trait]
path = 'lib/sips/sip-010-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.sbtc]
path = 'contracts/mocks/sbtc.clar'
clarity_version = 2
epoch = 2.4

[contracts.sample-dapp]
path = 'contracts/mocks/sample-dapp.clar'
clarity_version = 2
epoch = 2.4

[contracts.util]
path = 'contracts/util.clar'
clarity_version = 2
epoch = 2.4

[repl]
clarity_wasm_mode = false
show_timings = false

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
